### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jackmawer** [dividuum/mmbukkit#1]
Hi,
I discovered MinerMovies earlier today and have been enjoying the old recordings from back when I was just starting out with Minecraft. Seeing old recordings from servers I haven't visited in years is a special kind of nostalgia, and the unique way of being able to almost be a ghost in this world watching it unfold around you is almost magical.
It saddens me, then, to see that although the server is still online and operating, it seems to have not seen any love since 2014, being stuck on Minecraft 1.7.2. So, as this project is presumably long-abandoned by now, I wondered if you had the sources for the site still around somewhere?
I'm not particularly a skilled Java programmer, but the idea of this plugin combined with the site strikes me as an ideal anti-grief tool - tools like CoreProtect allow you to view logs of what players changed a certain block, but being able to *replay* whole game sessions would be incredibly useful for undoing damage caused by players, or even just looking back on an old session in years to come just as I am now.
Thanks for your time!

**Comment by dividuum** [comment]
Hey.

> It saddens me, then, to see that although the server is still online and operating, it seems to have not seen any love since 2014, being stuck on Minecraft 1.7.2.

Correct. Later versions changed how a player's identity is internally represented (UUID vs player name - this changed together with the ability to change your player name). I'm a bit fuzzy on details, but IIRC that made faking players, as required to serve replays, a lot harder due to cryptographically signed skins and Mojang couldn't give any guarantee that an [existing workaround](https://wiki.vg/Protocol#Spawn_Player) would be supported going forward. This pretty much demotivated me to support any later version and together with no real way to monetize (other than maybe serving garbage ads, which I would not do), this resulted in the project development being abandoned.

> So, as this project is presumably long-abandoned by now, I wondered if you had the sources for the site still around somewhere?

I still have the source code, but unlike the mmbukkit "plugin", all other code is written in Python/JS/HTML. And to be honest it's all pretty dated and probably not very useful at this point. The protocol parsing library itself is [available though](https://github.com/dividuum/fastmc) and includes some example code.

I think a more tightly couple approach within Minecraft/Bukkit itself is probably the better way to implement a similar feature in the future. The proxying (like MinersMovies did) is too fragile given the constantly changing protocol. If I understand it correctly, https://github.com/ReplayMod/ReplayMod does it like this for the client side.
